import { type Edge, type Node } from 'ng-diagram';
import {
  EdgeTemplateType,
  NodeTemplateType,
  type AvSchematicEdgeData,
  type AvSchematicNodeData,
} from './model/interfaces';

export const diagramModel: {
  nodes: Node<AvSchematicNodeData>[];
  edges: Edge<AvSchematicEdgeData>[];
} = {
  nodes: [
    {
      id: 'mic-1',
      type: NodeTemplateType.DeviceNode,
      position: { x: 60, y: 80 },
      data: {
        type: 'device',
        deviceId: 'MIC-1',
        manufacturer: 'Shure',
        model: 'SM58',
        category: 'microphone',
        location: 'Stage Center',
        ports: [{ id: 'out', label: 'OUT', direction: 'output', connectorType: 'XLR' }],
      },
    },
    {
      id: 'media-1',
      type: NodeTemplateType.DeviceNode,
      position: { x: 60, y: 380 },
      data: {
        type: 'device',
        deviceId: 'MEDIA-1',
        manufacturer: 'BrightSign',
        model: 'HD224',
        category: 'media-player',
        location: 'Rack 2U-1',
        ports: [
          { id: 'hdmi-out', label: 'HDMI', direction: 'output', connectorType: 'HDMI' },
          { id: 'audio-out', label: 'AUDIO', direction: 'output', connectorType: '3.5mm' },
        ],
      },
    },
    {
      id: 'mixer-1',
      type: NodeTemplateType.DeviceNode,
      position: { x: 580, y: 60 },
      data: {
        type: 'device',
        deviceId: 'MIXER-1',
        manufacturer: 'Yamaha',
        model: 'MG10XU',
        category: 'mixer',
        location: 'FOH Booth',
        ports: [
          { id: 'mic-1', label: 'MIC 1', direction: 'input', connectorType: 'XLR' },
          { id: 'mic-2', label: 'MIC 2', direction: 'input', connectorType: 'XLR' },
          { id: 'mic-3', label: 'MIC 3', direction: 'input', connectorType: 'XLR' },
          { id: 'mic-4', label: 'MIC 4', direction: 'input', connectorType: 'XLR' },
          { id: 'line-1', label: 'LINE 1', direction: 'input', connectorType: 'TRS' },
          { id: 'line-2', label: 'LINE 2', direction: 'input', connectorType: 'TRS' },
          { id: 'out-1', label: 'OUT 1', direction: 'output', connectorType: 'XLR' },
          { id: 'out-2', label: 'OUT 2', direction: 'output', connectorType: 'XLR' },
        ],
      },
    },
    {
      id: 'amp-1',
      type: NodeTemplateType.DeviceNode,
      position: { x: 1100, y: 60 },
      data: {
        type: 'device',
        deviceId: 'AMP-1',
        manufacturer: 'Crown',
        model: 'XLi 1500',
        category: 'amplifier',
        location: 'Rack 1U-3',
        ports: [
          { id: 'in-a', label: 'IN A', direction: 'input', connectorType: 'XLR' },
          { id: 'in-b', label: 'IN B', direction: 'input', connectorType: 'XLR' },
          { id: 'out-a', label: 'OUT A', direction: 'output', connectorType: 'Speakon' },
          { id: 'out-b', label: 'OUT B', direction: 'output', connectorType: 'Speakon' },
        ],
      },
    },
    {
      id: 'spk-1',
      type: NodeTemplateType.DeviceNode,
      position: { x: 1620, y: 40 },
      data: {
        type: 'device',
        deviceId: 'SPK-1',
        manufacturer: 'JBL',
        model: 'EON615',
        category: 'loudspeaker',
        location: 'Stage Left',
        ports: [{ id: 'in', label: 'IN', direction: 'input', connectorType: 'Speakon' }],
      },
    },
    {
      id: 'spk-2',
      type: NodeTemplateType.DeviceNode,
      position: { x: 1620, y: 280 },
      data: {
        type: 'device',
        deviceId: 'SPK-2',
        manufacturer: 'JBL',
        model: 'EON615',
        category: 'loudspeaker',
        location: 'Stage Right',
        ports: [{ id: 'in', label: 'IN', direction: 'input', connectorType: 'Speakon' }],
      },
    },
    {
      id: 'display-1',
      type: NodeTemplateType.DeviceNode,
      position: { x: 580, y: 540 },
      data: {
        type: 'device',
        deviceId: 'DISPLAY-1',
        manufacturer: 'NEC',
        model: 'E325',
        category: 'display',
        location: 'Lobby',
        ports: [{ id: 'hdmi-in', label: 'HDMI', direction: 'input', connectorType: 'HDMI' }],
      },
    },
  ],
  edges: [
    {
      id: 'wire-1',
      type: EdgeTemplateType.WireEdge,
      source: 'mic-1',
      sourcePort: 'out',
      target: 'mixer-1',
      targetPort: 'mic-1',
      data: { type: 'wire', wireId: 'W-001', wireType: 'audio' },
    },
    {
      id: 'wire-2',
      type: EdgeTemplateType.WireEdge,
      source: 'media-1',
      sourcePort: 'audio-out',
      target: 'mixer-1',
      targetPort: 'line-1',
      data: { type: 'wire', wireId: 'W-002', wireType: 'audio' },
    },
    {
      id: 'wire-3',
      type: EdgeTemplateType.WireEdge,
      source: 'media-1',
      sourcePort: 'hdmi-out',
      target: 'display-1',
      targetPort: 'hdmi-in',
      routingMode: 'manual',
      points: [
        { x: 307, y: 470 },
        { x: 510, y: 470 },
        { x: 510, y: 630 },
        { x: 573, y: 630 },
      ],
      data: { type: 'wire', wireId: 'W-003', wireType: 'video' },
    },
    {
      id: 'wire-4',
      type: EdgeTemplateType.WireEdge,
      source: 'mixer-1',
      sourcePort: 'out-1',
      target: 'amp-1',
      targetPort: 'in-a',
      data: { type: 'wire', wireId: 'W-004', wireType: 'audio' },
    },
    {
      id: 'wire-5',
      type: EdgeTemplateType.WireEdge,
      source: 'mixer-1',
      sourcePort: 'out-2',
      target: 'amp-1',
      targetPort: 'in-b',
      data: { type: 'wire', wireId: 'W-005', wireType: 'audio' },
    },
    {
      id: 'wire-6',
      type: EdgeTemplateType.WireEdge,
      source: 'amp-1',
      sourcePort: 'out-a',
      target: 'spk-1',
      targetPort: 'in',
      data: { type: 'wire', wireId: 'W-006', wireType: 'speaker' },
    },
    {
      id: 'wire-7',
      type: EdgeTemplateType.WireEdge,
      source: 'amp-1',
      sourcePort: 'out-b',
      target: 'spk-2',
      targetPort: 'in',
      data: { type: 'wire', wireId: 'W-007', wireType: 'speaker' },
    },
    {
      id: 'wire-8',
      type: EdgeTemplateType.WireEdge,
      source: 'media-1',
      sourcePort: 'audio-out',
      target: 'mixer-1',
      targetPort: 'mic-2',
      data: { type: 'wire', wireId: 'W-008', wireType: 'audio' },
    },
  ],
};
